on:
  push:
  release:
    types: [ "published" ]

jobs:
  linux-x86-64:
    name: "Linux x86-64"
    runs-on: "ubuntu-latest"
    steps:

      - name: "Checkout"  
        uses: "actions/checkout@v2"

      - name: "Install Build Dependencies"
        run: "sudo apt-get install -y libossp-uuid-dev"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1"
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: "1"
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
          DOTNET_NOLOGO: "1"
        with:
          dotnet-version: "6.0.x"

      - name: "Build Postgres"
        run: "./Protoculture.Postgres.Embedded/build-postgres-linux.sh"

      - name: "Test Integration"
        run: "dotnet test"

  windows-x86-64:
    name: "Windows x86-64"
    runs-on: "windows-latest"
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1"
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: "1"
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
          DOTNET_NOLOGO: "1"
        with:
          dotnet-version: "6.0.x"

      - name: "Build Postgres"
        run: "./Protoculture.Postgres.Embedded/build-postgres-windows.ps1"

      - name: "Test Integration"
        run: "dotnet test"

  package:
    name: "Package"
    runs-on: "ubuntu-latest"
    needs: [ "linux-x86-64", "windows-x86-64" ]
    steps:
      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1"
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: "1"
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
          DOTNET_NOLOGO: "1"
        with:
          dotnet-version: "6.0.x"
