on:
  push:
  release:
    types: [ published ]

jobs:
  linux:
    name: "Linux"
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: "1"
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
          DOTNET_NOLOGO: "1"
        with:
          dotnet-version: 6.0.x

  windows:
    name: "Windows"
    runs-on: "windows-latest"
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: "1"
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
          DOTNET_NOLOGO: "1"
        with:
          dotnet-version: 6.0.x
  
  package:
    name: "Package"
    runs-on: "ubuntu-latest"
    needs: [ linux, windows ]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: "1"
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
          DOTNET_NOLOGO: "1"
        with:
          dotnet-version: 6.0.x
